//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkomApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_event
    {
        public int id { get; set; }
        public string code { get; set; }
        public string event_name { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string place { get; set; }
        public Nullable<long> budget { get; set; }
        public int request_by { get; set; }
        public System.DateTime request_date { get; set; }
        public Nullable<System.DateTime> approve_date { get; set; }
        public Nullable<int> assign_to { get; set; }
        public Nullable<System.DateTime> closed_date { get; set; }
        public string note { get; set; }
        public Nullable<int> status { get; set; }
        public string reject_reason { get; set; }
        public Nullable<bool> is_delete { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> approve_by { get; set; }
    }
}
