//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkomApplication.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_souvenir_item
    {
        public int id { get; set; }
        public int t_souvenir_id { get; set; }
        public int m_souvenir_id { get; set; }
        public Nullable<long> qty { get; set; }
        public Nullable<long> qty_settlement { get; set; }
        public string note { get; set; }
        public bool is_delete { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
